### ISSUE TITLE
Delimiter options

### ISSUE THREAD

**Issue by yakspud** [GoetteSebastian/sketch-multi-lingual-plugin#1]
First off, thank you for this plugin! It does exactly what I need. I tried several others that use string variables, but yours is the best.

I modified my local version to use Tab as the delimiter rather than the semi-colon, since that makes it easy to paste text from a spreadsheet into the text file (or user can export as TSV). I think a nice feature would be able to select which character is the delimiter in the text file: semi-colon (current version), comma or tab key.

Again, great job on a very useful Sketch plugin that actually works and is easy to use!

**Comment by GoetteSebastian** [comment]
Check out the new Version 1.0.9. You can enter the delimeter in the dialog appearing after you choose your csv file. Cheers
